/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JiArchivo.java
 *
 * Created on 21/05/2013, 12:14:14 PM
 */

package testiisop;

import com.stin.BD.CatIntervencionDAO;
import com.stin.BD.CatSubIntervencionDAO;
import com.stin.BD.IntervencionDAO;
import com.stin.BD.PerforacionDAO;
import com.stin.BD.PozoDAO;
import com.stin.BD.PrintDocument;
import com.stin.BD.RmaDAO;
import com.stin.CatIntervencion;
import com.stin.CatSubIntervencion;
import com.stin.Intervencion;
import com.stin.Pozo;
import com.stin.model.Multivalor;
import com.stin.pemex.siop.model.Npt;
import com.stin.pemex.siop.reader.LeerExcel;
import com.stin.pemex.siop.reader.LeerNpts;
import com.stin.pemex.siop.util.TestClass;
import java.awt.Cursor;
import java.awt.Label;

import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Marco
 */
public class JiArchivo extends javax.swing.JInternalFrame {
 String fileName="";
    /** Creates new form JiArchivo */
    public JiArchivo() {
        initComponents();
        llenarIntervencion();
        comboSubIntervencion();
        //jRadioButton1.setVisible(false);
//            muestraIntervencion();
        jcbIntervencion.setSelectedIndex(0);
        jrbSIOP.setSelected(true);        
    }

    
    public void ocultaSubInter(){
        jLabel1.setVisible(false);
        JcbCatRma.setVisible(false);
    }
    public void muestraSubInter(){
        jLabel1.setVisible(true);
        JcbCatRma.setVisible(true);
    }
      public void ocultaIntervencion(){
        jblIntervencion.setVisible(false);
        jcbIntervencion.setVisible(false);
        jButton3.setEnabled(false);
    }
    public void muestraIntervencion(){
        jblIntervencion.setVisible(true);
        jcbIntervencion.setVisible(true);
        jButton3.setEnabled(true);
    }
    
    public void llenarIntervencion() {
        try {              
            jcbIntervencion.removeAllItems();
            List<CatIntervencion> lista=CatIntervencionDAO.getListCatIntervencion();                 
            for(CatIntervencion catInter: lista){            
                jcbIntervencion.addItem(new Multivalor(catInter.getIdTipo(), catInter.getStrNombre()));                
            }                     
        } catch (Exception e) {
            System.out.println("ERROR llenarIntervencion: " + e.getMessage());
        }
        
    }
    
     public void comboSubIntervencion(){
         JcbCatRma.removeAllItems();
        List<CatSubIntervencion>lista=CatSubIntervencionDAO.getListCatSubIntervencion(true, "");
        for(CatSubIntervencion c:lista){
            JcbCatRma.addItem(new Multivalor(c.getIdCatSubIntervencion(), c.getStrNombre()));
        }
        lista=null;
    }
     
     public void cargarPozos(){
        try {
                //CARGA COMBO BOX CON POZOS
                jComboBox1.removeAllItems();
                List<Intervencion> pozos = PozoDAO.getListPozoByIntervencion(((Multivalor)jcbIntervencion.getSelectedItem()).getIndice(),
                        ((Multivalor)JcbCatRma.getSelectedItem()).getIndice());//getListPozo(true,"");
                //jComboBox1.setEnabled(true);
                jComboBox1.addItem(new Multivalor(0, "--- Seleccione pozo ---"));
                for(Intervencion p:pozos){                                    
                    jComboBox1.addItem(new Multivalor(p.getPozo().getIdPozo(), p.getPozo().getStrNombre()));
                }
                //cnn.close();
            } catch (Exception e) {
                System.out.println("ERROR-Combobox: " + e.getMessage());
            }
    }
    
     
  
    
     public void limpiar(String mensaje){
        lblNotificaciones.setText(mensaje);
        jTextField1.setText("");
        jComboBox1.setSelectedIndex(0);
        //jComboBox1.setEnabled(false);   
        //ocultaIntervencion();        
        jButton2.setEnabled(false);             
        jrbSIOP.setSelected(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jrbSIOP = new javax.swing.JRadioButton();
        jrbNPT = new javax.swing.JRadioButton();
        jcbIntervencion = new javax.swing.JComboBox();
        jblIntervencion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JcbCatRma = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNotificaciones = new java.awt.Label();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("1.- Informacíon a Cargar"));

        buttonGroup1.add(jrbSIOP);
        jrbSIOP.setLabel("SIOP");
        jrbSIOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSIOPActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbNPT);
        jrbNPT.setText("PLANTILLA");
        jrbNPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNPTActionPerformed(evt);
            }
        });

        jcbIntervencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbIntervencionActionPerformed(evt);
            }
        });

        jblIntervencion.setText("Intervención");

        jLabel1.setText("Tipo Intervencion");

        JcbCatRma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbCatRmaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("PROGRAMA");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(jrbSIOP)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jrbNPT)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jRadioButton1))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(JcbCatRma, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jblIntervencion)
                                .add(10, 10, 10)
                                .add(jcbIntervencion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jrbSIOP)
                    .add(jrbNPT)
                    .add(jRadioButton1))
                .add(7, 7, 7)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(3, 3, 3)
                        .add(jblIntervencion))
                    .add(jcbIntervencion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(JcbCatRma, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("2.- Seleccionar Archivo"));
        jPanel2.setMaximumSize(null);

        jButton1.setText("Buscar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jButton1)
                .add(18, 18, 18)
                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 283, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("3.- Seleccionar Pozo"));
        jPanel3.setMaximumSize(null);

        jButton2.setText("Guardar");
        jButton2.setActionCommand("");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Visualizar");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel3Layout.createSequentialGroup()
                        .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 393, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jButton3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .add(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(411, Short.MAX_VALUE)
                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(95, 95, 95))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testiisop/resources/pemex/logo_pemex.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel3.setForeground(new java.awt.Color(38, 148, 105));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SIOP / PLANTILLA");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblNotificaciones.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel5))
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 254, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 246, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lblNotificaciones, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .add(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel3)
                    .add(jLabel5))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 83, Short.MAX_VALUE)
                .add(lblNotificaciones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbSIOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSIOPActionPerformed
        // TODO add your handling code here:
/*        if(jrbSIOP.isSelected()){
            ocultaIntervencion();
            ocultaSubInter();
        }
 */
}//GEN-LAST:event_jrbSIOPActionPerformed

    private void jrbNPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNPTActionPerformed
        // TODO add your handling code here:
        if (jrbNPT.isSelected()){
            llenarIntervencion();
            comboSubIntervencion();
//            muestraIntervencion();
            jcbIntervencion.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jrbNPTActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Filtro
        lblNotificaciones.setText(" ");
        
        FileNameExtensionFilter xlsFilter = new FileNameExtensionFilter("Archivo Excel 2003", "xls");
        FileNameExtensionFilter xlsxFilter = new FileNameExtensionFilter("Archivo Excel 2007 - 2010", "xlsx");
        
        JFileChooser fs = new JFileChooser();
        fs.setFileFilter(xlsFilter);
        fs.setFileFilter(xlsxFilter);
        fs.setDialogTitle("Abrir SIOP");
        int result = fs.showOpenDialog(null);
        if (result == fs.APPROVE_OPTION) {
            //PATH
            File pathFile = fs.getSelectedFile();
            //FILE NAME
            fileName= fs.getSelectedFile().getName();
            jTextField1.setText(String.valueOf(pathFile));
            jButton2.setEnabled(true);    
            jButton3.setEnabled(true);
            System.out.println("FILE NAME: " + fileName);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
   
    public void lectura(int lectura) {        
        try {            
            String excelName = jTextField1.getText().trim();
            //Informacion del Pozo
            Multivalor miPozo = (Multivalor) jComboBox1.getSelectedItem();
            int index = miPozo.getIndice();            
            Multivalor intTipo = (Multivalor) jcbIntervencion.getSelectedItem();            
            int tipo = intTipo.getIndice();            
            
            System.out.println(excelName);
            
            String mensaje = "";
            boolean bandera = true;
            if (jrbSIOP.isSelected()) {
                LeerExcel leerSIOP = new LeerExcel(excelName);
                lblNotificaciones.setEnabled(true);
                lblNotificaciones.setText("Cargando.....");
//                mensaje=leerSIOP.excutedSIOPReader(index);
                //System.out.println("IDPOZO: " + index + " Intervencion: " + tipo + " IDINTERVENICON: " + getIntervencion(index, tipo));
                mensaje = leerSIOP.excutedSIOPReader(getIntervencion(index, tipo));
            } else {
                int tipoInter = ((Multivalor) jcbIntervencion.getSelectedItem()).getIndice();
                String namePozo = ((Multivalor) jComboBox1.getSelectedItem()).getValor();
                
                if (lectura == 1) {
                    if (jRadioButton1.isSelected()) {
                        System.out.println("entró");
                        switch (tipoInter) {
                            case 1:
                                
                                System.out.println("1");
                                mensaje = LeerNpts.insertaPrograma(LeerNpts.getProgramaPerforacion(excelName, getIntervencion(index, tipo)));
                                break;
                            case 2:
                                System.out.println("2");
                                mensaje = LeerNpts.insertaPrograma(LeerNpts.getProgramaTerminacion(excelName, getIntervencion(index, tipo)));
                                break;
                            case 3:
                                System.out.println("3");
                                mensaje = LeerNpts.insertaPrograma(LeerNpts.getProgramaRMA(excelName, getIntervencion(index, tipo)));
                                break;
                        }
                        
                    } else {
                        switch (tipoInter) {
                            case 1:
                                mensaje = LeerNpts.insertaNpts(getListNpts(excelName, index, "PERFORACIÓN", 1, true), 1);
                                break;
                            case 2:
                                // mensaje=LeerNpts.insertaNpts(getListNpts(excelName,index,"PERFORACIÓN",1,true),1);
                                mensaje = LeerNpts.insertaNpts(getListNpts(excelName, index, "TERMINACIÓN", 2, true), 2);
                                break;
                            case 3:
                                mensaje = LeerNpts.insertaNpts(getListNpts(excelName, index, "RMA", 3, true), 3);
                                break;
                        }
                    }
                } else {
                    bandera = false;

                    //verificar si esta seleccionado programas 
                    
                    if (jRadioButton1.isSelected()) {
                        System.out.println("entró visualizar ");
                        switch (tipoInter) {
                            case 1:
                                
                                System.out.println("1");
                                //List<Programas>listaProgramas,int tipo,String namePozo,String inter)
                                PrintDocument.PrintPrograma(LeerNpts.getProgramaPerforacion(excelName, getIntervencion(index, tipo)), 1, namePozo, "PERFORACIÓN");
                                break;
                            case 2:
                                System.out.println("2");
                                PrintDocument.PrintPrograma(LeerNpts.getProgramaTerminacion(excelName, getIntervencion(index, tipo)), 2, namePozo, "TERMINACIÓN");
                                break;
                            case 3:
                                System.out.println("3");
                                PrintDocument.PrintPrograma(LeerNpts.getProgramaRMA(excelName, getIntervencion(index, tipo)), 1, namePozo, "REPARACIÓN MAYOR");
                                break;
                        }
                        
                    } else {

                        //si no
                        switch (tipoInter) {
                            case 1:
                                PrintDocument.Print(getListNpts(excelName, index, "PERFORACIÓN", 1, false), 1, namePozo, "PERFORACIÓN", ultimoConse);
                                break;
                            case 2:
                                //PrintDocument.Print(getListNpts(excelName,index,"PERFORACIÓN",1,false),1,namePozo,"PERFORACIÓN",ultimoConse);
                                PrintDocument.Print(getListNpts(excelName, index, "TERMINACIÓN", 2, false), 2, namePozo, "TERMINACIÓN", ultimoConse);
                                break;
                            case 3:
                                PrintDocument.Print(getListNpts(excelName, index, "RMA", 3, false), 3, namePozo, "REPARACIÓN MAYOR", ultimoConse);
                                break;
                        }
                    }
                }
            }
            lblNotificaciones.setText(mensaje);
            if (mensaje.equals("") && bandera) {
                limpiar("Archivo " + fileName + " leido Correctamente");
            }
            
        } catch (Exception e) {
            System.out.println("SIOP Reader error: " + e.getMessage());            
            e.getStackTrace();
        }
        
    }
    int ultimoConse = 0;
    public List<Npt>getListNpts(String excelName, int index,String textBuscar,int tipo,boolean visualiza){
       
        int intervencion =getIntervencion(index,tipo);
        System.out.println("INTERVENCION: " + intervencion + " IDPOZO= " + index + " INTER: " +tipo);        
        boolean existe=true;      
        try {        
//            if (!(intervencion>0)){                                
//                intervencion= IntervencionDAO.insertIntervencion(tipo,index).getIdIntervencion();  //INSERTA LA INTERVENCION Y DEVUELVE EL ID DE LA INTERVENCION INSERTADA
//                existe=false;                    
//            }

//            if (existe) {    //OBTENER EL ULTIMO CONSECUTIVO
                ultimoConse = PerforacionDAO.searchPerfConseByInter(intervencion, tipo);//es el id de la intervencion
                System.out.println("ULTIMOcONSE: " + ultimoConse + " iDINTERVENCION: " + intervencion);
//            } 
            
        } 
        catch (Exception e) {
        }
        LeerNpts npts = new LeerNpts();
        List<Npt>lista=npts.leerExcelNPT(excelName,index,intervencion,tipo,existe,textBuscar,visualiza,ultimoConse); // Intervencion es el id                                
        return lista;
    }
    public int getIntervencion(int index,int tipo){
        int idSubInter=1;
        int verfica=((Multivalor)jcbIntervencion.getSelectedItem()).getIndice();
        if (verfica==3){
            idSubInter=((Multivalor)JcbCatRma.getSelectedItem()).getIndice();
        }
        return IntervencionDAO.searchIntervencionByTipoAndPozo(index,tipo,idSubInter);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (jComboBox1.getSelectedIndex()!=0){
            lectura(1);
        }else{
            lblNotificaciones.setText("Seleccione un pozo");
        }
        setCursor(null);
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        lectura(0);
        setCursor(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        Menu.posX--;
        Menu.menuArchivo=3;
    }//GEN-LAST:event_formInternalFrameClosed

    private void jcbIntervencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbIntervencionActionPerformed
        // TODO add your handling code here:
        try {
            JcbCatRma.setSelectedIndex(0);
            cargarPozos();
            if (jcbIntervencion.getSelectedIndex()==2){
                muestraSubInter();
            }else{
                ocultaSubInter();
            }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jcbIntervencionActionPerformed

    private void JcbCatRmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbCatRmaActionPerformed
        // TODO add your handling code here:
        try {
            cargarPozos();
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_JcbCatRmaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JcbCatRma;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jblIntervencion;
    private javax.swing.JComboBox jcbIntervencion;
    private javax.swing.JRadioButton jrbNPT;
    private javax.swing.JRadioButton jrbSIOP;
    private java.awt.Label lblNotificaciones;
    // End of variables declaration//GEN-END:variables

}
